### ISSUE TITLE
Wowace support

### ISSUE THREAD

**Issue by tekkub** [p3lim/addon-packager-proxy#13]
Lovely little app you've got here, I've needed something like this for a *long* time.

It seems as though curse has multiple instances of its "forge" available, for example I host all my addons on wowace.  This means they have URLs like `https://www.wowace.com/projects/picodps`.  If you try to access it [through the curseforge domain](https://wow.curseforge.com/projects/picodps) you just get a 404.  Maybe instead of taking the slug (`picodps`) portion of the URL and constructing the rest of it around that, you could just take a full URL in the json file that lists the addon mappings?  That would be a quick fix for folks that use wowace or some other incantation of the curseforge (if there are any).

In my local instance of the proxy I just changed the `curseURL` variable in packager.js, but that was just a quick hack to make it work for me.

**Comment by p3lim** [comment]
I'll take a look at it when I get a chance, currently busy with exams.

**Comment by tekkub** [comment]
<3

There's no rush here, my local instance is working just fine.  I just figured you'd want to know about this.

**Comment by p3lim** [comment]
I've been toying with the idea of writing my own packager running on Travis CI, which would allow independency from Curse and avoiding the need for hosting the application, simplifying the setup for the user. This also allows for easy notifications both on GitHub directly through integration, as well as alternatives like sending the user an email on a build/deploy failure.

Not that hard, just a bit time consuming.

**Comment by p3lim** [comment]
That commit adds an environment variable that can be set to manually force a specific curse url to be used, as I can't find a way to properly detect whether the project is on wowace or curseforge.

**Comment by tekkub** [comment]
❤️   Yea, as far as I can tell the only thing you could do is if the curseforge URL for the project 404s, try the wowace one instead.  An env variable works perfectly for me.
