### ISSUE TITLE
[0.72] Forced Check doesn't set details.github_repository

### ISSUE THREAD

**Issue by Choonster** [p3lim/addon-packager-proxy#14]
When a request is sent to `/force/:repo/:tag`, the `details` object passed to the `Packager` function never has the `github_repository` property set. This means that the application tries to clone `undefined` when fetching the changelog.

Now that you're getting the repository URL from the webhook payload, I'm not sure exactly how you'd get it in the forced check.

Since the application is already downloading the AddOn to upload to WoWI, would it be easier to unzip it and use the changelog file from there?

**Comment by p3lim** [comment]
> Since the application is already downloading the AddOn to upload to WoWI, would it be easier to unzip it and use the changelog file from there?

That's what I did previously, but as changelogs are optional I can't really rely on this.
I suppose in reality I could, just not submit a changelog if the file is not present.
