### ISSUE TITLE
Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by Choonster** [p3lim/addon-packager-proxy#16]
When running a forced check for a recent release, I received this error:
```
[LOG.1] Attempting to fetch changelog from path "CHANGELOG.md".

/app/node_modules/adm-zip/zipFile.js:66
            throw Utils.Errors.INVALID_FORMAT;
                              ^
Invalid or unsupported zip format. No END header found
``` 

I'm using the latest commit on the `dev` branch, 622a47a9a51c0fa4459dda370af99a7987ff375f.

You can find the release on CurseForge [here](https://wow.curseforge.com/projects/custom-tooltips/files/2412560).

You can view the full log [here](https://gist.github.com/Choonster/d712fc6ee3bf9abab5cfa854c9dd32ca).

**Comment by p3lim** [comment]
Will take a look when I get the time, no guarantees for the following month though, exam time.

**Comment by p3lim** [comment]
Was this recurring or just a single time?

**Comment by Choonster** [comment]
It was recurring, but I'm now getting a different error: #17.

**Comment by Choonster** [comment]
No longer happening in 0.7.3 (362508d90ec1d14f05f1755c3cabd767135608ef).
