### ISSUE TITLE
Could not find tag link on CurseForge.

### ISSUE THREAD

**Issue by Choonster** [p3lim/addon-packager-proxy#17]
When running a forced check for the same release as #16, I'm now receiving this error:
```
Could not find tag link on CurseForge.
```

I'm using the latest commit on the `dev` branch, 622a47a9a51c0fa4459dda370af99a7987ff375f.

You can find the release on CurseForge [here](https://wow.curseforge.com/projects/custom-tooltips/files/2412560).

You can find the AddOn list JSON file [here](https://gist.github.com/Choonster/2ce79d3eb7adee8bdb2d).

You can view the full log [here](https://gist.github.com/Choonster/f311407f1d9cbca6870b04f75bf72ed3).

I haven't changed anything since reporting #16, I'm not sure why the error has changed.

**Comment by p3lim** [comment]
Update to latest master then force restart your dynos.
Report back if you're still getting this error.

**Comment by Choonster** [comment]
Fixed in 0.7.3 (362508d90ec1d14f05f1755c3cabd767135608ef).

**Comment by p3lim** [comment]
https://github.com/p3lim/addon-packager-proxy/commit/73f37a218aa4253bee08878beaa7107405d65025 to be precise.
